[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.32.1"

[programs.localnet]
presale = "EBotmNK5mEQX5U3pc6JH5vmAygX1zKtgspycDMs6arqF"

[programs.devnet]
presale = "EBotmNK5mEQX5U3pc6JH5vmAygX1zKtgspycDMs6arqF"

[programs.mainnet]
presale = "EBotmNK5mEQX5U3pc6JH5vmAygX1zKtgspycDMs6arqF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
